/**
 * Central env abstraction.
 * Vite exposes APPWRITE_* from root env as VITE_APPWRITE_* via vite.config.js
 * and all resource IDs are required from env (no hardcoded runtime IDs).
 */

const required = [
  "VITE_APPWRITE_ENDPOINT",
  "VITE_APPWRITE_PROJECT_ID",
  "VITE_APPWRITE_DATABASE_ID",
  "VITE_APPWRITE_COLLECTION_USERS_PROFILE",
  "VITE_APPWRITE_COLLECTION_MATERIAL_CATEGORIES",
  "VITE_APPWRITE_COLLECTION_MATERIALS",
  "VITE_APPWRITE_COLLECTION_CLIENTS",
  "VITE_APPWRITE_COLLECTION_DRIVERS",
  "VITE_APPWRITE_COLLECTION_TRUCKS",
  "VITE_APPWRITE_COLLECTION_PLANTS",
  "VITE_APPWRITE_COLLECTION_VOUCHERS",
  "VITE_APPWRITE_COLLECTION_TICKETS",
  "VITE_APPWRITE_COLLECTION_PRINT_LOGS",
  "VITE_APPWRITE_COLLECTION_AUDIT_LOGS",
  "VITE_APPWRITE_COLLECTION_SYSTEM_CONFIG",
  "VITE_APPWRITE_COLLECTION_ROLES",
  "VITE_APPWRITE_COLLECTION_PERMISSIONS_CATALOG",
  "VITE_APPWRITE_COLLECTION_ROLE_PERMISSIONS",
  "VITE_APPWRITE_COLLECTION_COUNTER_SALES",
  "VITE_APPWRITE_COLLECTION_WEIGHT_LOGS",
  "VITE_APPWRITE_COLLECTION_SCAN_LOGS",
  "VITE_APPWRITE_BUCKET_MATERIAL_IMAGES",
  "VITE_APPWRITE_FUNCTION_CREATE_USER",
  "VITE_APPWRITE_FUNCTION_SETUP_OWNER",
  "VITE_APPWRITE_FUNCTION_SYNC_USER_NAME",
  "VITE_APPWRITE_DOC_SYSTEM_CONFIG_SINGLETON",
];

for (const key of required) {
  if (!import.meta.env[key]) {
    throw new Error(
      `Variable de entorno ${key} no definida. Verifica .env.local`,
    );
  }
}

const get = (key) => import.meta.env[key];

export const ENV = {
  appwrite: {
    endpoint: get("VITE_APPWRITE_ENDPOINT"),
    projectId: get("VITE_APPWRITE_PROJECT_ID"),
    databaseId: get("VITE_APPWRITE_DATABASE_ID"),
    collections: {
      USERS_PROFILE: get("VITE_APPWRITE_COLLECTION_USERS_PROFILE"),
      MATERIAL_CATEGORIES: get("VITE_APPWRITE_COLLECTION_MATERIAL_CATEGORIES"),
      MATERIALS: get("VITE_APPWRITE_COLLECTION_MATERIALS"),
      CLIENTS: get("VITE_APPWRITE_COLLECTION_CLIENTS"),
      DRIVERS: get("VITE_APPWRITE_COLLECTION_DRIVERS"),
      TRUCKS: get("VITE_APPWRITE_COLLECTION_TRUCKS"),
      PLANTS: get("VITE_APPWRITE_COLLECTION_PLANTS"),
      VOUCHERS: get("VITE_APPWRITE_COLLECTION_VOUCHERS"),
      TICKETS: get("VITE_APPWRITE_COLLECTION_TICKETS"),
      PRINT_LOGS: get("VITE_APPWRITE_COLLECTION_PRINT_LOGS"),
      AUDIT_LOGS: get("VITE_APPWRITE_COLLECTION_AUDIT_LOGS"),
      SYSTEM_CONFIG: get("VITE_APPWRITE_COLLECTION_SYSTEM_CONFIG"),
      ROLES: get("VITE_APPWRITE_COLLECTION_ROLES"),
      PERMISSIONS_CATALOG: get("VITE_APPWRITE_COLLECTION_PERMISSIONS_CATALOG"),
      ROLE_PERMISSIONS: get("VITE_APPWRITE_COLLECTION_ROLE_PERMISSIONS"),
      COUNTER_SALES: get("VITE_APPWRITE_COLLECTION_COUNTER_SALES"),
      WEIGHT_LOGS: get("VITE_APPWRITE_COLLECTION_WEIGHT_LOGS"),
      SCAN_LOGS: get("VITE_APPWRITE_COLLECTION_SCAN_LOGS"),
    },
    buckets: {
      MATERIAL_IMAGES: get("VITE_APPWRITE_BUCKET_MATERIAL_IMAGES"),
    },
    functions: {
      CREATE_USER: get("VITE_APPWRITE_FUNCTION_CREATE_USER"),
      SETUP_OWNER: get("VITE_APPWRITE_FUNCTION_SETUP_OWNER"),
      SYNC_USER_NAME: get("VITE_APPWRITE_FUNCTION_SYNC_USER_NAME"),
    },
    docs: {
      SYSTEM_CONFIG_SINGLETON: get("VITE_APPWRITE_DOC_SYSTEM_CONFIG_SINGLETON"),
    },
  },
  // Optional metadata:
  // system: { version: get("VITE_APP_VERSION") }
};

export default ENV;
